### ISSUE TITLE
Binary cache missing?

### ISSUE THREAD

**Issue by musjj** [viperML/nh#53]
The `outputs.out.path` of the latest commit is (checked with `nix derivation show`):

```
/nix/store/zj7qll22jg1zjpxr88yf4alsr9fqaxg1-nh-3.4.14
```

The binary cache seems to be generally available:

```bash
$ curl https://viperml.cachix.org/nix-cache-info                          
StoreDir: /nix/store
WantMassQuery: 1
Priority: 41
```

But, the latest derivation is not:

```bash
$ curl https://viperml.cachix.org/zj7qll22jg1zjpxr88yf4alsr9fqaxg1.narinfo
404 - Not Found
```

Looking at the CI [job](https://github.com/viperML/nh/actions/runs/7210993064/job/19645376647):

```
copying 3 paths...
copying path '/nix/store/alkam8rwi865x2vfjxh7hqmvf2ay7zzz-Cargo.lock' to 'http://127.0.0.1:37515/'...
copying path '/nix/store/zj7qll22jg1zjpxr88yf4alsr9fqaxg1-nh-3.4.14' to 'http://127.0.0.1:37515/'...
copying path '/nix/store/nyf4lc8q1f8ka2ia72nm7y0znw2fpqd2-cargo-vendor-dir' to 'http://127.0.0.1:37515/'...
  2023-12-14T15:29:29.416408Z  INFO magic_nix_cache: Shutting down
    at magic-nix-cache/src/main.rs:189
```

It should've been copied already. What went wrong here?

**Comment by viperML** [comment]
Hello, at some point in the past, I changed the CI job to use the magic-nix-cache instead of the cachix action, meaning that the artifacts are not pushed to cachix (but instead, kept in the GH action cache). As I use the free tier cachix account, and share it between multiple repos, I'd like to keep the usage to a minimum.

I have not updated the readme.md to reflect these changes.

Nh is already available in nixpkgs, so you can grab a pretty recent version simply from the nixpkgs cache.

**Comment by musjj** [comment]
> Nh is already available in nixpkgs, so you can grab a pretty recent version simply from the nixpkgs cache.

Thanks, I forgot to check `unstable`.
