### ISSUE TITLE
Network transparency

### ISSUE THREAD

**Issue by viperML** [viperML/nh#7]
New deployment tool let's go

**Comment by viperML** [comment]
Ideally abstract away commands that:
- Run on the "build system"
- Run on the "host System"

Basically a similar abstraction to cross compilation, but applied to "running commands"

**Comment by Hubro** [comment]
Just to clarify, is `nh` currently able to deploy to remote hosts using `<EXTRA_ARGS>`? I don't see any mention of it anywhere, but for all I know that just means it's too obvious to explicitly document and I'm stupid :sweat_smile:

---

I have a big hacky `justfile` with commands for `switch`, `boot`, `test` etc. that handles the cruft of deploying to remote systems. I was hoping to replace `nixos-rebuild` with `nh` since the UX looks amazing.

**Comment by viperML** [comment]
No, this issue means that there's nothing inplemented about remote systems

**Comment by viperML** [comment]
testing stuff on #107

**Comment by charmoniumQ** [comment]
> Just to clarify, is `nh` currently able to deploy to remote hosts using `<EXTRA_ARGS>`? I don't see any mention of it anywhere, but for all I know that just means it's too obvious to explicitly document and I'm stupid 😅

`EXTRA_ARGS` get passed to `nix build` not to `nixos-rebuild`. `nixos-rebuild` is the one that supports `--target-host`.

> I have a big hacky `justfile` with commands for `switch`, `boot`, `test` etc. that handles the cruft of deploying to remote systems. I was hoping to replace `nixos-rebuild` with `nh` since the UX looks amazing.

I do that, but with the apps in `flake.nix`, so I can do `nix run .#appName -- args`. If you already have Nix, you don't particularly need Just, unless you want to use advanced Just features.

**Comment by viperML** [comment]
I think I don't have the bandwidth to retrofit a network-transparency abstraction into NH, given that there are already many deployment tools and NH wouldn't fit any niche.

**Comment by diniamo** [comment]
It would fit the niche of me not having to use multiple.

What other ones are there?

**Comment by viperML** [comment]
https://wiki.nixos.org/wiki/Applications#Deployment
