### ISSUE TITLE
`FLAKE` is not a very specific env var

### ISSUE THREAD

**Issue by dpc** [viperML/nh#88]
I just watched https://www.youtube.com/watch?v=DnA4xNTrrqY and I like the idea.

`FLAKE` is a very generic name for an env var and I'd prefer something like `NIXOS_CONF_FLAKE` or `NH_OS_FLAKE` (good practice to prefix globals like this with a name of a tool).

**Comment by viperML** [comment]
I've had `NH_FLAKE` in the back of my mind, but at the same time haven't found any project that also uses `FLAKE`. Perhaps it is possible to parse both from the environment, with priority to the latter

**Comment by dpc** [comment]
Definitely possible. I thought about `_OS_` if `nh` was to handle more stuff. I don't know if that's the plan. One might have "NixOS configuration flake" and then some other flakes.

**Comment by Adda0** [comment]
I agree that something like `NH_OS_FLAKE` or even `NH_NIXOS_FLAKE`, and maybe in the future `NH_<OTHER>_FLAKE` would be a great descriptive and conflict-free solution.

**Comment by viperML** [comment]
You can use [wrapper-manager](https://github.com/viperML/wrapper-manager) to wrap nh and not pollute the global environment

**Comment by Adda0** [comment]
That is a very interesting project indeed. This approach would solve this issue for me.

**Comment by x3rAx** [comment]
I'd love to see something like `NH_OS_FLAKE` and `NH_HOME_FLAKE` used by the commands `nh os` and `nh home` respectively, with a fallback to a general `NH_FLAKE` (or just `FLAKE` or whatever) when the command specific variable is not set

Or maybe don't use `NH_FLAKE` at all and simply support `FLAKE` just for backwards compatibility, since I don't know of a way to have the os/home config in the same flake other using the "home manager in system config" approach. But I guess in that case, you can't build home manager independently fom your system anyways?

**Comment by Adda0** [comment]
To get on the same page, may I ask what is the conclusion from this discussion which resulted in closing the issue? What is the recommented approach we should use now?

**Comment by viperML** [comment]
nh will use `NH_FLAKE` as of 4.0 for any installable

**Comment by viperML** [comment]
For the record, I don't know how I could reuse the same `Installable` clap `Args`, and use a different env variable depending on the context.

**Comment by viperML** [comment]
Related: #174
