### ISSUE TITLE
Does nh support configuration.nix or just nix flakes?

### ISSUE THREAD

**Issue by concur1** [viperML/nh#91]
Sorry if this is not the right place for this question.

I am not using flakes currently but I have seem vimjoyers video (https://www.youtube.com/watch?v=DnA4xNTrrqY) and would like to try out using nh.

If it only supports flakes it might be worth linking to other projects that support configuration.nix.

Thanks!

**Comment by viperML** [comment]
It doesn't, partly because I don't like the behaviour of nixos-rebuild when dealing with regular nix files (too many implicit moving parts). I would do my own take on regular configuration.nix handling, but that would be incompatible with what nixos-rebuild does, so I'd rather not introduce that friction point.

**Comment by concur1** [comment]
> It doesn't, partly because I don't like the behaviour of nixos-rebuild when dealing with regular nix files (too many implicit moving parts). I would do my own take on regular configuration.nix handling, but that would be incompatible with what nixos-rebuild does, so I'd rather not introduce that friction point.

Ok, thanks, that makes sense
